/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:98cfda01-9615-45a4-ab12-db0607fdd2b9",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_OAIOLOlq6",
  aws_user_pools_web_client_id: "4o563hgvk152tdbe55ie9kei1d",
  oauth: {},
  aws_user_files_s3_bucket:
    "reactwebcameraprojec92390922fba8472293aff5204d6200549-dev",
  aws_user_files_s3_bucket_region: "us-east-1",
};

export default awsmobile;
